import React, { useState, useEffect, useRef } from 'react';
import { useParams, useLocation, useNavigate } from 'react-router-dom';
import { ArrowLeft, Calendar, Download, FileText, Loader2, RefreshCw } from 'lucide-react';
import { clsx, type ClassValue } from 'clsx';
import { twMerge } from 'tailwind-merge';
import { motion } from 'motion/react';

function cn(...inputs: ClassValue[]) {
    return twMerge(clsx(inputs));
}

interface Issue {
    id: number;
    subject: string;
    tracker: string;
    status: string;
    priority: string;
    created_on: string;
    due_date: string | null;
    assigned_to: string;
}

interface ProjectIssuesResponse {
    project_id: number;
    project_name: string;
    date_from: string;
    date_to: string;
    total: number;
    issues: Issue[];
}

const STATUS_STYLES: Record<string, string> = {
    'Résolu': 'bg-emerald-100 text-emerald-700',
    'Clôturé': 'bg-slate-100   text-slate-700',
    'Fermé': 'bg-slate-100   text-slate-700',
    'En cours': 'bg-amber-100   text-amber-700',
    'Ouvert': 'bg-blue-100    text-blue-700',
    'Test': 'bg-indigo-100  text-indigo-700',
    'Bloqué': 'bg-red-100     text-red-700',
    'Validation': 'bg-purple-100  text-purple-700',
};

const PRIORITY_STYLES: Record<string, string> = {
    'Critique': 'bg-red-500    text-white',
    'Urgente': 'bg-red-500    text-white',
    'Haute': 'bg-orange-500 text-white',
    'Majeure': 'bg-orange-500 text-white',
    'Normale': 'bg-emerald-500 text-white',
    'Mineure': 'bg-emerald-500 text-white',
    'Basse': 'bg-slate-400  text-white',
};

// Default date helpers
const today = () => new Date().toISOString().slice(0, 10);
const sixMonthsAgo = () => {
    const d = new Date();
    d.setMonth(d.getMonth() - 6);
    return d.toISOString().slice(0, 10);
};

export default function ProjectDetail() {
    const { projectId } = useParams<{ projectId: string }>();
    const location = useLocation();
    const navigate = useNavigate();
    const reportRef = useRef<HTMLDivElement>(null);

    const projectName: string =
        (location.state as any)?.project_name ?? `Projet #${projectId}`;

    const [dateFrom, setDateFrom] = useState(sixMonthsAgo());
    const [dateTo, setDateTo] = useState(today());

    const [data, setData] = useState<ProjectIssuesResponse | null>(null);
    const [loading, setLoading] = useState(false);
    const [pdfLoading, setPdfLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);

    const API = 'http://localhost:8000';

    const fetchIssues = async () => {
        setLoading(true);
        setError(null);
        const controller = new AbortController();
        const timeoutId = setTimeout(() => controller.abort(), 5000);

        try {
            const params = new URLSearchParams({
                date_from: dateFrom,
                date_to: dateTo,
                project_name: projectName,
            });
            const res = await fetch(
                `${API}/api/projects/${projectId}/issues?${params}`,
                { signal: controller.signal }
            );
            clearTimeout(timeoutId);
            if (!res.ok) throw new Error(`Erreur ${res.status}`);
            const json: ProjectIssuesResponse = await res.json();
            setData(json);
        } catch (e: any) {
            console.error("Fetch issues error:", e);
            setError(e.name === 'AbortError' ? "Le serveur Redmine met trop de temps à répondre (Timeout)." : (e.message ?? 'Erreur inconnue'));
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => { fetchIssues(); }, []);

    const downloadPDF = async () => {
        setPdfLoading(true);
        try {
            const html2pdf = (window as any).html2pdf;
            if (!html2pdf) throw new Error("La librairie PDF n'est pas chargée.");

            // Fetch the responsive template generated by Python/Jinja2
            const response = await fetch(`http://127.0.0.1:8000/api/projects/${projectId}/template?date_from=${dateFrom}&date_to=${dateTo}&project_name=${encodeURIComponent(projectName)}`);
            if (!response.ok) throw new Error("Impossible de récupérer le template du rapport.");

            const htmlContent = await response.text();

            // Create a temporary container to render the fetched HTML
            const worker = document.createElement('div');
            worker.innerHTML = htmlContent;
            document.body.appendChild(worker);

            const opt = {
                margin: 10,
                filename: `rapport_${projectId}_${dateFrom}_${dateTo}.pdf`,
                image: { type: 'jpeg', quality: 0.98 },
                html2canvas: { scale: 2, useCORS: true, letterRendering: true },
                jsPDF: { unit: 'mm', format: 'a4', orientation: 'landscape' }
            };

            await html2pdf().set(opt).from(worker).save();
            document.body.removeChild(worker);
        } catch (e: any) {
            console.error("PDF Generate Error:", e);
            alert(`Erreur Rapport : ${e.message}`);
        } finally {
            setPdfLoading(false);
        }
    };

    const issues = data?.issues ?? [];

    // Calculate granular status breakdown
    const statusBreakdown = issues.reduce((acc: Record<string, number>, issue) => {
        acc[issue.status] = (acc[issue.status] || 0) + 1;
        return acc;
    }, {});

    // Sort statuses by count (highest first)
    const sortedStatuses = Object.entries(statusBreakdown).sort((a, b) => b[1] - a[1]);

    const statusCardColors: Record<string, string> = {
        'Résolu': 'bg-emerald-600',
        'Clôturé': 'bg-slate-600',
        'En cours': 'bg-orange-500',
        'Ouvert': 'bg-indigo-600',
        'Nouveau': 'bg-blue-600',
        'Bloqué': 'bg-red-600',
        'Validation': 'bg-purple-600',
        'Test': 'bg-cyan-600',
    };

    const resolvedCount = issues.filter(i => ['Résolu', 'Clôturé', 'Fermé'].includes(i.status)).length;
    const rate = issues.length > 0
        ? ((resolvedCount / issues.length) * 100).toFixed(1)
        : '0';

    return (
        <div className="min-h-screen bg-[#F8FAFC] pb-16 font-sans">
            {/* Header */}
            <header className="bg-white px-8 py-5 shadow-sm border-b border-slate-100 no-print">
                <div className="mx-auto flex max-w-7xl items-center gap-4">
                    <button
                        onClick={() => navigate('/')}
                        className="flex items-center gap-2 text-sm text-slate-500 hover:text-indigo-600 transition-colors"
                    >
                        <ArrowLeft size={16} />
                        Retour
                    </button>
                    <div className="h-5 w-px bg-slate-200" />
                    <div>
                        <h1 className="text-xl font-bold text-slate-900">{projectName}</h1>
                        <p className="text-xs text-slate-400">Rapport d'activité par projet</p>
                    </div>
                </div>
            </header>

            <main className="mx-auto mt-8 max-w-7xl px-8 space-y-8">

                {/* Date range filters - skip in PDF */}
                <section className="rounded-2xl bg-white p-6 shadow-sm border border-slate-100 no-print">
                    <h2 className="mb-4 text-sm font-bold text-slate-700 flex items-center gap-2">
                        <Calendar size={16} className="text-indigo-500" />
                        Sélectionner la période
                    </h2>
                    <div className="flex flex-wrap items-end gap-4">
                        <div className="flex flex-col gap-1">
                            <label className="text-[10px] font-semibold uppercase tracking-wider text-slate-400">Du</label>
                            <input
                                type="date"
                                value={dateFrom}
                                onChange={e => setDateFrom(e.target.value)}
                                className="rounded-lg border border-slate-200 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-400"
                            />
                        </div>
                        <div className="flex flex-col gap-1">
                            <label className="text-[10px] font-semibold uppercase tracking-wider text-slate-400">Au</label>
                            <input
                                type="date"
                                value={dateTo}
                                onChange={e => setDateTo(e.target.value)}
                                className="rounded-lg border border-slate-200 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-400"
                            />
                        </div>
                        <button
                            onClick={fetchIssues}
                            disabled={loading}
                            className="flex items-center gap-2 rounded-lg bg-indigo-600 px-5 py-2.5 text-sm font-semibold text-white shadow hover:bg-indigo-700 disabled:opacity-60 transition-all"
                        >
                            {loading ? <Loader2 size={15} className="animate-spin" /> : <RefreshCw size={15} />}
                            Filtrer
                        </button>
                    </div>
                </section>

                {error && (
                    <div className="rounded-xl border border-red-200 bg-red-50 px-5 py-3 text-sm text-red-700">
                        ⚠️ {error}
                    </div>
                )}

                {/* REPORT CONTENT AREA - This is what gets captured into PDF */}
                <div ref={reportRef} className="bg-[#F8FAFC] p-4 rounded-xl">
                    {/* Report Header (Only for PDF context usually, but good to see) */}
                    <div className="hidden print-only mb-8 flex justify-between items-start border-b pb-6">
                        <div>
                            <h1 className="text-2xl font-bold text-slate-900">Rapport d'activité Maintenance</h1>
                            <p className="text-lg text-indigo-600 font-semibold">{projectName}</p>
                        </div>
                        <div className="text-right text-xs text-slate-400">
                            <p>Période : {dateFrom} au {dateTo}</p>
                            <p>Généré le : {new Date().toLocaleDateString('fr-FR')}</p>
                        </div>
                    </div>

                    {/* Stats Cards */}
                    {!loading && data && (
                        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
                            <div className="rounded-2xl bg-slate-900 p-6 text-white shadow-md">
                                <p className="text-sm opacity-80 uppercase font-bold tracking-wider">Total tickets</p>
                                <p className="text-4xl font-bold mt-1">{issues.length}</p>
                                <p className="text-xs mt-3 opacity-70">Taux de résolution: {rate}%</p>
                            </div>
                            {sortedStatuses.slice(0, 3).map(([status, count]) => (
                                <div key={status} className={cn("rounded-2xl p-6 text-white shadow-md", statusCardColors[status] || 'bg-indigo-600')}>
                                    <p className="text-sm opacity-80 uppercase font-bold tracking-wider">{status}</p>
                                    <p className="text-4xl font-bold mt-1">{count}</p>
                                    <p className="text-xs mt-3 opacity-70">Nombre de tickets</p>
                                </div>
                            ))}
                        </div>
                    )}

                    {/* Tickets Table */}
                    <section className="rounded-2xl bg-white shadow-sm border border-slate-100 overflow-hidden">
                        <div className="flex items-center justify-between border-b border-slate-100 bg-slate-50/50 px-6 py-4">
                            <h3 className="text-sm font-bold text-slate-800">Détail des tickets de la période</h3>
                            <span className="text-[10px] font-medium text-slate-400">
                                {loading ? '…' : `${issues.length} ticket(s)`}
                            </span>
                        </div>

                        {loading ? (
                            <div className="flex items-center justify-center py-20 text-slate-400">
                                <Loader2 size={28} className="animate-spin mr-3" />
                                Chargement…
                            </div>
                        ) : (
                            <div className="overflow-x-auto">
                                <table className="w-full text-left">
                                    <thead>
                                        <tr className="border-b border-slate-100 text-[10px] font-bold uppercase tracking-wider text-slate-400">
                                            <th className="px-6 py-4">ID</th>
                                            <th className="px-6 py-4">Titre</th>
                                            <th className="px-6 py-4">Tracker</th>
                                            <th className="px-6 py-4">Statut</th>
                                            <th className="px-6 py-4">Priorité</th>
                                            <th className="px-6 py-4">Ouverture</th>
                                            <th className="px-6 py-4">Échéance</th>
                                        </tr>
                                    </thead>
                                    <tbody className="divide-y divide-slate-50">
                                        {issues.length === 0 ? (
                                            <tr>
                                                <td colSpan={7} className="px-6 py-12 text-center text-sm text-slate-400">
                                                    Aucun ticket trouvé sur cette période.
                                                </td>
                                            </tr>
                                        ) : issues.map(issue => (
                                            <tr key={issue.id} className="transition-colors border-b border-slate-50">
                                                <td className="px-6 py-3 text-xs font-bold text-indigo-600">#{issue.id}</td>
                                                <td className="px-6 py-3 text-xs font-medium text-slate-700">{issue.subject}</td>
                                                <td className="px-6 py-3">
                                                    <span className="rounded bg-blue-50 border border-blue-100 px-2 py-0.5 text-[10px] font-semibold text-blue-700">
                                                        {issue.tracker}
                                                    </span>
                                                </td>
                                                <td className="px-6 py-3">
                                                    <span className={cn(
                                                        'rounded-full px-2.5 py-0.5 text-[10px] font-semibold',
                                                        STATUS_STYLES[issue.status] ?? 'bg-slate-100 text-slate-600'
                                                    )}>
                                                        {issue.status}
                                                    </span>
                                                </td>
                                                <td className="px-6 py-3">
                                                    <span className={cn(
                                                        'rounded px-2 py-0.5 text-[10px] font-bold uppercase',
                                                        PRIORITY_STYLES[issue.priority] ?? 'bg-slate-300 text-slate-700'
                                                    )}>
                                                        {issue.priority}
                                                    </span>
                                                </td>
                                                <td className="px-6 py-3 text-xs text-slate-500 whitespace-nowrap">{issue.created_on}</td>
                                                <td className="px-6 py-3 text-xs text-slate-500 whitespace-nowrap">{issue.due_date ?? '—'}</td>
                                            </tr>
                                        ))}
                                    </tbody>
                                </table>
                            </div>
                        )}
                    </section>
                </div>

                {/* Generate PDF Button */}
                <div className="flex justify-end no-print">
                    <button
                        onClick={downloadPDF}
                        disabled={pdfLoading || issues.length === 0}
                        className="flex items-center gap-2.5 rounded-xl bg-gradient-to-r from-indigo-600 to-purple-600 px-7 py-3.5 text-sm font-bold text-white shadow-lg hover:shadow-xl hover:scale-[1.02] disabled:opacity-50 disabled:scale-100 transition-all duration-200"
                    >
                        {pdfLoading ? (
                            <Loader2 size={18} className="animate-spin" />
                        ) : (
                            <Download size={18} />
                        )}
                        {pdfLoading ? 'Génération en cours…' : 'Effectuer le rapport d\'activité (PDF)'}
                        {!pdfLoading && <FileText size={16} className="opacity-70" />}
                    </button>
                </div>
            </main>

            <style>{`
        @media print {
            .no-print { display: none !important; }
            .print-only { display: block !important; }
        }
        .print-only { display: none; }

        /* Fix for html2canvas/oklch error: force standard colors in the report area */
        [ref="reportRef"], #report-content, .bg-[#F8FAFC] {
            --color-indigo-600: #4f46e5 !important;
            --color-emerald-600: #059669 !important;
            --color-orange-500: #f97316 !important;
            --color-slate-900: #0f172a !important;
            --color-slate-400: #94a3b8 !important;
            --color-slate-100: #f1f5f9 !important;
            --color-slate-50: #f8fafc !important;
            --color-blue-50: #eff6ff !important;
            --color-blue-100: #dbeafe !important;
            --color-blue-700: #1d4ed8 !important;
        }
        
        /* Force background and text colors to be non-oklch for html2canvas */
        .bg-indigo-600 { background-color: #4f46e5 !important; }
        .bg-emerald-600 { background-color: #059669 !important; }
        .bg-orange-500 { background-color: #f97316 !important; }
        .bg-emerald-500 { background-color: #10b981 !important; }
        .bg-red-500 { background-color: #ef4444 !important; }
        .text-indigo-600 { color: #4f46e5 !important; }
        .text-slate-900 { color: #0f172a !important; }
        .text-slate-400 { color: #94a3b8 !important; }
        .bg-white { background-color: #ffffff !important; }
        .bg-slate-50\\/50 { background-color: rgba(248, 250, 252, 0.5) !important; }
        .border-slate-100 { border-color: #f1f5f9 !important; }
        
        /* Status Badges */
        .bg-emerald-100 { background-color: #dcfce7 !important; }
        .text-emerald-700 { color: #15803d !important; }
        .bg-slate-100 { background-color: #f1f5f9 !important; }
        .text-slate-700 { color: #334155 !important; }
        .bg-amber-100 { background-color: #fef3c7 !important; }
        .text-amber-700 { color: #b45309 !important; }
        .bg-blue-100 { background-color: #dbeafe !important; }
        .text-blue-700 { color: #1d4ed8 !important; }
        .bg-indigo-100 { background-color: #e0e7ff !important; }
        .text-indigo-700 { color: #4338ca !important; }
        .bg-red-100 { background-color: #fee2e2 !important; }
        .text-red-700 { color: #b91c1c !important; }
        .bg-purple-100 { background-color: #f3e8ff !important; }
        .text-purple-700 { color: #7e22ce !important; }
      `}</style>
        </div>
    );
}
